server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhaysingh28350/Config_Server
          default-label: main
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics